volumes:
  peer0.org4.example.com:

networks:
  test:
    name: fabric_test

services:

  peer0.org4.example.com:
    container_name: peer0.org4.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      # Peer identity
      - CORE_PEER_ID=peer0.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP

      # Peer networking (UNIQUE PORTS)
      - CORE_PEER_ADDRESS=peer0.org4.example.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051

      # Chaincode
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.example.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052

      # Gossip
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.example.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.example.com:12051

      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s

    volumes:
      - ../../organizations/peerOrganizations/org4.example.com/peers/peer0.org4.example.com:/etc/hyperledger/fabric
      - peer0.org4.example.com:/var/hyperledger/production

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    ports:
      - 12051:12051

    networks:
      - test
